name: Node.js CI (SQLite)

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Prepare SQLite test database
      - name: Setup SQLite test DB
        run: |
          mkdir -p ./server/db
          rm -f ./server/db/test.sqlite
          npx knex migrate:latest --knexfile ./server/db/knexfile.js --env test
          npx knex seed:run --knexfile ./server/db/knexfile.js --env test


      # 5. Run tests
      - name: Run backend tests
        run: npm run test
        env:
          NODE_ENV: test
