name: Node.js CI (SQLite)

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Prepare SQLite database
        run: |
          rm -f ./server/db/test.sqlite
          npx knex migrate:latest --env test
          npx knex seed:run --env test

      - name: Run tests
        run: npm run test
        env:
          NODE_ENV: test
